"""Add ESG scorecard tables

Revision ID: efc1226184dd
Revises: 
Create Date: 2025-09-20 09:38:12.020223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc1226184dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environmental_score', sa.Numeric(), nullable=True),
    sa.Column('social_score', sa.Numeric(), nullable=True),
    sa.Column('governance_score', sa.Numeric(), nullable=True),
    sa.Column('final_esg_score', sa.Numeric(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reporting_period', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_dashboard_id'), 'esg_dashboard', ['id'], unique=False)
    op.create_table('esg_kpis',
    sa.Column('kpi_code', sa.String(), nullable=False),
    sa.Column('kpi_description', sa.String(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('normalization_method', sa.String(), nullable=True),
    sa.Column('framework_reference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('kpi_code')
    )
    op.create_index(op.f('ix_esg_kpis_kpi_code'), 'esg_kpis', ['kpi_code'], unique=False)
    op.create_table('esg_pillar_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('pillar_weight', sa.Numeric(), nullable=True),
    sa.Column('pillar_score', sa.Numeric(), nullable=True),
    sa.Column('weighted_contribution', sa.Numeric(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reporting_period', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_pillar_scores_id'), 'esg_pillar_scores', ['id'], unique=False)
    op.create_table('esg_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_code', sa.String(), nullable=True),
    sa.Column('user_weightage', sa.Numeric(), nullable=True),
    sa.Column('normalized_score', sa.Numeric(), nullable=True),
    sa.Column('weighted_score', sa.Numeric(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reporting_period', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['kpi_code'], ['esg_kpis.kpi_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_scores_id'), 'esg_scores', ['id'], unique=False)
    op.drop_table('esg_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('esg_metrics_pkey'))
    )
    op.drop_index(op.f('ix_esg_scores_id'), table_name='esg_scores')
    op.drop_table('esg_scores')
    op.drop_index(op.f('ix_esg_pillar_scores_id'), table_name='esg_pillar_scores')
    op.drop_table('esg_pillar_scores')
    op.drop_index(op.f('ix_esg_kpis_kpi_code'), table_name='esg_kpis')
    op.drop_table('esg_kpis')
    op.drop_index(op.f('ix_esg_dashboard_id'), table_name='esg_dashboard')
    op.drop_table('esg_dashboard')
    # ### end Alembic commands ###
